from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from db.database import engine
from models import Item


items = [
    {
        "titre": "SQL Injection",
        "categorie": "Web",
        "description": "Injection de commandes SQL malveillantes dans une application qui communique avec une base de données.",
        "image_url": "",
        "annee": 1998,
        "type": "Injection",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Cross-Site Scripting (XSS)",
        "categorie": "Web",
        "description": "Injection de code JavaScript malveillant dans une page web consultée par d'autres utilisateurs.",
        "image_url": "",
        "annee": 1996,
        "type": "Injection",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "CSRF",
        "categorie": "Web",
        "description": "Attaque qui force un utilisateur authentifié à effectuer une action qu'il n'a pas volontairement demandée.",
        "image_url": "",
        "annee": 2001,
        "type": "Exploitation Web",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "HTTP Request Smuggling",
        "categorie": "Web",
        "description": "Technique exploitant une différence d'interprétation des requêtes HTTP entre plusieurs serveurs.",
        "image_url": "",
        "annee": 2005,
        "type": "Contournement",
        "niveau": "Avancé",
    },
    {
        "titre": "SSRF",
        "categorie": "Web",
        "description": "Attaque permettant de faire effectuer des requêtes réseau à un serveur vulnérable.",
        "image_url": "",
        "annee": 2010,
        "type": "Requête forgée",
        "niveau": "Avancé",
    },
    {
        "titre": "ARP Spoofing",
        "categorie": "Réseau",
        "description": "Usurpation d'adresses ARP afin de rediriger le trafic réseau vers une machine contrôlée.",
        "image_url": "",
        "annee": 1990,
        "type": "Usurpation",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "DNS Spoofing",
        "categorie": "Réseau",
        "description": "Modification ou falsification des réponses DNS afin de rediriger une victime vers une autre adresse.",
        "image_url": "",
        "annee": 1990,
        "type": "Usurpation",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "IP Spoofing",
        "categorie": "Réseau",
        "description": "Falsification de l'adresse IP source d'un paquet réseau.",
        "image_url": "",
        "annee": 1985,
        "type": "Usurpation",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "DDoS",
        "categorie": "Réseau",
        "description": "Saturation d'un service ou d'une infrastructure à l'aide d'un grand nombre de requêtes provenant de plusieurs machines.",
        "image_url": "",
        "annee": 1999,
        "type": "Déni de service",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Man-in-the-Middle",
        "categorie": "Réseau",
        "description": "Interception des communications entre deux parties par un attaquant qui s'interpose entre elles.",
        "image_url": "",
        "annee": 1980,
        "type": "Interception",
        "niveau": "Avancé",
    },
    {
        "titre": "Phishing",
        "categorie": "Ingénierie sociale",
        "description": "Technique utilisant des messages frauduleux pour inciter une victime à communiquer des informations sensibles.",
        "image_url": "",
        "annee": 1995,
        "type": "Hameçonnage",
        "niveau": "Débutant",
    },
    {
        "titre": "Spear Phishing",
        "categorie": "Ingénierie sociale",
        "description": "Forme ciblée de phishing visant une personne ou une organisation précise.",
        "image_url": "",
        "annee": 2003,
        "type": "Hameçonnage ciblé",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Vishing",
        "categorie": "Ingénierie sociale",
        "description": "Technique de manipulation utilisant les appels téléphoniques ou la voix pour tromper une victime.",
        "image_url": "",
        "annee": 2006,
        "type": "Ingénierie sociale",
        "niveau": "Débutant",
    },
    {
        "titre": "Smishing",
        "categorie": "Ingénierie sociale",
        "description": "Phishing réalisé par l'intermédiaire de SMS ou de messages mobiles.",
        "image_url": "",
        "annee": 2008,
        "type": "Ingénierie sociale",
        "niveau": "Débutant",
    },
    {
        "titre": "Pretexting",
        "categorie": "Ingénierie sociale",
        "description": "Création d'un faux scénario pour obtenir des informations ou provoquer une action de la victime.",
        "image_url": "",
        "annee": 1990,
        "type": "Manipulation",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Buffer Overflow",
        "categorie": "Système",
        "description": "Exploitation d'un dépassement de mémoire tampon pour modifier le comportement d'un programme.",
        "image_url": "",
        "annee": 1988,
        "type": "Corruption mémoire",
        "niveau": "Avancé",
    },
    {
        "titre": "Privilege Escalation",
        "categorie": "Système",
        "description": "Exploitation permettant à un utilisateur ou processus d'obtenir des privilèges supérieurs à ceux qui lui sont normalement accordés.",
        "image_url": "",
        "annee": 1990,
        "type": "Élévation de privilèges",
        "niveau": "Avancé",
    },
    {
        "titre": "DLL Hijacking",
        "categorie": "Système",
        "description": "Détournement du chargement d'une bibliothèque DLL afin de faire exécuter du code malveillant.",
        "image_url": "",
        "annee": 2000,
        "type": "Détournement",
        "niveau": "Avancé",
    },
    {
        "titre": "Rootkit",
        "categorie": "Système",
        "description": "Logiciel conçu pour maintenir un accès privilégié tout en dissimulant sa présence.",
        "image_url": "",
        "annee": 1990,
        "type": "Dissimulation",
        "niveau": "Avancé",
    },
    {
        "titre": "Race Condition",
        "categorie": "Système",
        "description": "Exploitation d'une condition de concurrence lorsque le résultat dépend de l'ordre d'exécution de plusieurs opérations.",
        "image_url": "",
        "annee": 1970,
        "type": "Condition de concurrence",
        "niveau": "Avancé",
    },
    {
        "titre": "Brute Force",
        "categorie": "Authentification",
        "description": "Tentative systématique de nombreuses combinaisons afin de trouver un mot de passe ou un secret.",
        "image_url": "",
        "annee": 1970,
        "type": "Devination",
        "niveau": "Débutant",
    },
    {
        "titre": "Credential Stuffing",
        "categorie": "Authentification",
        "description": "Utilisation automatisée d'identifiants volés sur différents services afin de trouver des comptes réutilisant les mêmes mots de passe.",
        "image_url": "",
        "annee": 2014,
        "type": "Réutilisation d'identifiants",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Password Spraying",
        "categorie": "Authentification",
        "description": "Tentative d'un petit nombre de mots de passe courants sur un grand nombre de comptes.",
        "image_url": "",
        "annee": 2010,
        "type": "Devination",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Session Hijacking",
        "categorie": "Authentification",
        "description": "Prise de contrôle d'une session utilisateur authentifiée.",
        "image_url": "",
        "annee": 1990,
        "type": "Détournement de session",
        "niveau": "Avancé",
    },
    {
        "titre": "Credential Theft",
        "categorie": "Authentification",
        "description": "Vol d'identifiants d'authentification tels que des mots de passe ou des jetons.",
        "image_url": "",
        "annee": 1980,
        "type": "Vol d'identifiants",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Evil Twin",
        "categorie": "Wi-Fi",
        "description": "Création d'un faux point d'accès Wi-Fi imitant un réseau légitime afin d'attirer les utilisateurs.",
        "image_url": "",
        "annee": 2000,
        "type": "Point d'accès malveillant",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Wi-Fi Deauthentication",
        "categorie": "Wi-Fi",
        "description": "Envoi de trames de désauthentification afin de provoquer la déconnexion de clients Wi-Fi.",
        "image_url": "",
        "annee": 2009,
        "type": "Déconnexion forcée",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "KRACK",
        "categorie": "Wi-Fi",
        "description": "Famille d'attaques exploitant une faiblesse du protocole WPA2 lors de la négociation d'une connexion Wi-Fi.",
        "image_url": "",
        "annee": 2017,
        "type": "Exploitation cryptographique",
        "niveau": "Avancé",
    },
    {
        "titre": "Wi-Fi Eavesdropping",
        "categorie": "Wi-Fi",
        "description": "Écoute non autorisée des communications transitant sur un réseau Wi-Fi.",
        "image_url": "",
        "annee": 1997,
        "type": "Écoute réseau",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "WPS PIN Attack",
        "categorie": "Wi-Fi",
        "description": "Exploitation du mécanisme PIN de WPS afin de tenter de retrouver les informations permettant l'accès au réseau.",
        "image_url": "",
        "annee": 2011,
        "type": "Force brute",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Man-in-the-Cloud",
        "categorie": "Cloud",
        "description": "Attaque visant les mécanismes de synchronisation cloud afin de détourner une session ou un compte.",
        "image_url": "",
        "annee": 2015,
        "type": "Détournement de session",
        "niveau": "Avancé",
    },
    {
        "titre": "Cloud Account Hijacking",
        "categorie": "Cloud",
        "description": "Compromission d'un compte cloud afin d'accéder aux ressources et données associées.",
        "image_url": "",
        "annee": 2010,
        "type": "Compromission de compte",
        "niveau": "Avancé",
    },
    {
        "titre": "Cloud Cryptojacking",
        "categorie": "Cloud",
        "description": "Utilisation non autorisée de ressources cloud pour effectuer du minage de cryptomonnaies.",
        "image_url": "",
        "annee": 2017,
        "type": "Abus de ressources",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Cloud Misconfiguration Exploitation",
        "categorie": "Cloud",
        "description": "Exploitation d'une mauvaise configuration d'un service cloud permettant un accès non autorisé.",
        "image_url": "",
        "annee": 2010,
        "type": "Mauvaise configuration",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Cloud API Abuse",
        "categorie": "Cloud",
        "description": "Exploitation ou utilisation abusive d'une API cloud afin d'accéder à des ressources ou fonctionnalités.",
        "image_url": "",
        "annee": 2010,
        "type": "Abus d'API",
        "niveau": "Avancé",
    },
    {
        "titre": "Ransomware",
        "categorie": "Malware",
        "description": "Logiciel malveillant qui bloque ou chiffre des données afin d'exiger une rançon.",
        "image_url": "",
        "annee": 1989,
        "type": "Extorsion",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Trojan Horse",
        "categorie": "Malware",
        "description": "Programme malveillant se présentant comme un logiciel légitime afin de tromper l'utilisateur.",
        "image_url": "",
        "annee": 1970,
        "type": "Logiciel malveillant",
        "niveau": "Débutant",
    },
    {
        "titre": "Computer Worm",
        "categorie": "Malware",
        "description": "Programme malveillant capable de se reproduire et de se propager automatiquement entre systèmes.",
        "image_url": "",
        "annee": 1988,
        "type": "Auto-propagation",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Spyware",
        "categorie": "Malware",
        "description": "Logiciel malveillant conçu pour surveiller les activités d'un utilisateur et collecter des informations.",
        "image_url": "",
        "annee": 1995,
        "type": "Espionnage",
        "niveau": "Intermédiaire",
    },
    {
        "titre": "Botnet",
        "categorie": "Malware",
        "description": "Réseau de machines compromises contrôlées à distance par un attaquant.",
        "image_url": "",
        "annee": 1999,
        "type": "Réseau de machines compromises",
        "niveau": "Intermédiaire",
    },
]


async def seed_items() -> None:
    async with AsyncSession(engine) as session:
        for item_data in items:
            statement = select(Item).where(Item.titre == item_data["titre"])
            result = await session.exec(statement)

            if result.first() is None:
                session.add(Item(**item_data))

        await session.commit()


if __name__ == "__main__":
    import asyncio

    asyncio.run(seed_items())
    print(f"{len(items)} attaques vérifiées.")